version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: mysecureuser    # Change this
      ME_CONFIG_BASICAUTH_PASSWORD: mysecurepass    # Change this
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/?authSource=admin
    depends_on:
      - mongo


volumes:
  mongo_data:
    driver: local
